version: '3.8'
services:
  apache:
    image: httpd:alpine
    container_name: apache
    network_mode: testNet

  backend:
    build:
      context: ../path/to/your/backend/
      dockerfile: Dockerfile
    container_name: main-service-backend
    network_mode: testNet
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
